name: Build release zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ZIP plugin
        run: |
          cd ..
          mv ${{ github.event.repository.name }} add-infos-to-the-events-calendar
          zip -r -q add-infos-to-the-events-calendar.zip add-infos-to-the-events-calendar/* -x "*/.git/*" "*/.github/*" "*/phpcs.xml" "*/composer.json" "*/composer.lock" "*/readme.md" "*/.gitignore" "*/vendor/*" "*/svn/*" "*/releases/*"
          cp add-infos-to-the-events-calendar.zip add-infos-to-the-events-calendar/
          mv add-infos-to-the-events-calendar ${{ github.event.repository.name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: add-infos-to-the-events-calendar.zip
